### ISSUE TITLE
[Help Wanted / Question] Running ChampSim Tracer

### ISSUE THREAD

**Issue by yogeshmo** [ChampSim/ChampSim#100]
I'm trying to create a trace, but I'm not exactly sure what steps I should be following.

I ran `./make_tracer.sh`, but I keep getting the following error:
`makefile:15: /Config/makefile.default.rules: No such file or directory
make: *** No rule to make target '/Config/makefile.default.rules'.  Stop.`

Can someone help me out?

**Comment by GinoAC** [comment]
In make_tracer.sh, change the PIN_TOOL path to match where your pintool is located.

**Comment by yogeshmo** [comment]
This worked, thank you!
