### ISSUE TITLE
Cloudsuite traces

### ISSUE THREAD

**Issue by manaal22152** [ChampSim/ChampSim#116]
How to run Cloudsuite traces on ChampSim?

**Comment by ngober** [comment]
The cloudsuite traces were used for CRC2 and can be found on the page for that contest (linked in the README). The cloudsuite traces are the ones with a separate trace for each core.

**Comment by manaal22152** [comment]
I want to know if there is a different way to run CloudSuite traces? I get error when I run them. I used the traces from the CRC2 page. I see there in main.cc that there is a different parameter for cloudsuite. But I am not sure how to use it.

**Comment by alberto-ros** [comment]
You need to add the option -c to the command line.
