### ISSUE TITLE
-nan average miss latency

### ISSUE THREAD

**Issue by ArnauPrat** [ChampSim/ChampSim#118]
Hi all, I have the following output obtained from the 602.gcc_s-1850B.champsimtrace.xz trace.
It reports an average "L1I AVERAGE MISS LATENCY: -nan cycles latency" 

It looks like a bug to me. Is that correct?

Thanks

[602.gcc_s-1850B.champsimtrace.xz-bimodal-no-no-no-no-lru-1core.txt](https://github.com/ChampSim/ChampSim/files/5854858/602.gcc_s-1850B.champsimtrace.xz-bimodal-no-no-no-no-lru-1core.txt)

**Comment by itisntalex** [comment]
You trace specifies that you have no misses in the L1I which means that you're dividing by 0. That's why.

**Comment by ArnauPrat** [comment]
I Understand. Thanks for your prompt response.

**Comment by ngober** [comment]
I'm closing this because it appears to be resolved. If this is not the case, let me know and I can reopen it for further discussion.
