### ISSUE TITLE
Tracing the whole program

### ISSUE THREAD

**Issue by mahmoodn** [ChampSim/ChampSim#14]
How can I specify the whole duration of the program while creating a trace? Example of 

```
pin -t obj/champsim_tracer.so -o traces/ls_trace.champsim -s 100000 -t 200000 -- ls
```
says tracing 200K instructions. Let's assume `ls` program finishes before 200K instructions. What will happen then? The trace has less than 200K instructions? 

Or assume that `ls` has more than 200K instructions. How we can fix that then?

**Comment by itisntalex** [comment]
I have little experience with tracing and especially with PinTool but from my understanding, I believe you have to slightly modify the `void EndInstruction ()` that is defined [here](https://github.com/ChampSim/ChampSim/blob/6956933bd4cc4dbe196c7af99fbb626dc2792f47/tracer/champsim_tracer.cpp#L113) in pintool provided with ChampSim.

I'm going to make an example here:

```cpp
void EndInstruction()
{
    //printf("%d]\n", (int)instrCount);

    //printf("\n");

    if(instrCount > KnobSkipInstructions.Value())
    {
        tracing_on = true;

        if(instrCount <= (KnobTraceInstructions.Value()+KnobSkipInstructions.Value()))
        {
            // keep tracing
            fwrite(&curr_instr, sizeof(trace_instr_format_t), 1, out);
        }
        else
        {
            tracing_on = false;
            // close down the file, we're done tracing
            if(!output_file_closed)
            {
                fclose(out);
                output_file_closed = true;
            }

            exit(0);
        }
    }
}
```

The first `if` allows you to just trace when you exceeded the given number of instructions to skip. The nested `if` stands for tracing instructions only if you didn't exceed `KnobTraceInstructions.Value()+KnobSkipInstructions.Value()`. I believe you should remove that nested `if` while keeping the `fwrite` call. And somehow, you should think about the clean-up with `fclose` and so on.

About the moment you reach the end of the execution; I reckon the pintool while simply stop and call the `Fini` function (clean should probably happen there).

Hope you found that helpful. 😄
