### ISSUE TITLE
How to get ".bpred" file

### ISSUE THREAD

**Issue by AminAvan** [ChampSim/ChampSim#140]
Hi
I download [TAGE-SC-L](https://www.jilp.org/cbp2016/program.html), then I want to get `.bpred` file from it, how can I do it?
In addition, what is the `.bpred` file, is it a compiled file?
Bests

**Comment by ngober** [comment]
The `*.bpred` files are simply C++ source files with a different file extension. The build system copies the `*.bpred` file into a `*.cc` file before compilation.

There has been some confusion and complaint about this, understandably, and in the next (hopefully soon) release of ChampSim, this custom file extension will be removed in favor of normal C++ convention.
