### ISSUE TITLE
make_tracer.sh will not correctly build tracer

### ISSUE THREAD

**Issue by zlukegord** [ChampSim/ChampSim#16]
I have been trying to build tracer so I can generate some traces for research I am doing. I changed the pin tool path in make_tracer.sh to be the correct location of my pin tool, but it still does not run properly. It fails and gives the following errors:
https://pastebin.com/unxiqrqB
I'm using pin version 3.11, and g++ 5.4.0

Is there anything I can do to get tracer working?

**Comment by mahmoodn** [comment]
> champsim_tracer.cpp:46:6: error: ‘string’ was not declared in this scope

Use `std::string`

**Comment by zlukegord** [comment]
Thank you!
