### ISSUE TITLE
Develop Branch - Simulating 2MB pages

### ISSUE THREAD

**Issue by gvavou5** [ChampSim/ChampSim#162]
I want to simulate a baseline system with 2MB pages and compare it against a system with 4KB pages. To do so, I create a new configuration which is the same as the provided one except that the page size is 2097152, instead of 4096. 

I have some questions regarding the virtual memory implementation.

1. in the function PageTableWalker::get_offset (ptw.cc file) you declare shift = 12; I believe that it should be declared as LOG2_PAGE_SIZE. The same applies for the function PagingStructureCache::get_index (ptw.cc file).

2.  in the function PageTableWalker::get_offset (ptw.cc file)  you declare uint64_t offset = (full_virtual_addr >> shift) & 0x1ff; I believe that the mask should take into account the page size. Thus, 0x1ff if page size = 4kb and 0xfff if page size = 2mb.

Is it correct what I am saying or do I miss something in the implementation?

**Comment by ngober** [comment]
I've proposed #172 to address this. In it, it properly applies `LOG2_PAGE_SIZE` and the masking bits.

**Comment by ngober** [comment]
Resolving after the merge of #172.
