### ISSUE TITLE
SPEC 2017 Trace Question

### ISSUE THREAD

**Issue by nikolaniko** [ChampSim/ChampSim#164]
Hi all, 

For the SPEC 2017 traces generated by Professor Daniel Jiménez, what is the purpose of the numbers after the benchmark name? For example, for the trace 657.xz_s-56B.champsimtrace.xz, what does 56B mean?

Thank you, 
Nick

**Comment by ngober** [comment]
That is the number of instructions skipped before collecting the trace. It is chosen according to the SimPoint methodology.
