### ISSUE TITLE
[question] why these benchmarks?

### ISSUE THREAD

**Issue by truewindgg** [ChampSim/ChampSim#168]
these are so many benchmarks in http://hpca23.cse.tamu.edu/champsim-traces/speccpu/
why chose these benchmarks in [../scripts/dpc3_max_simpoint.txt](https://github.com/ChampSim/ChampSim/blob/master/scripts/dpc3_max_simpoint.txt)

thank you

**Comment by ngober** [comment]
There is nothing particularly special about these traces. There are many traces available for use with ChampSim.
