### ISSUE TITLE
Issue with generating traces using ChampSimTracer on Pin 3.2

### ISSUE THREAD

**Issue by dark-AIP** [ChampSim/ChampSim#169]
I followed the instruction on champsim page to the end when I need to run (pin -t obj-intel64/champsim_tracer.so -- <your program here>)

and since I need only change -t as the parameter, I ran this: _pin -t obj-intel64/champsim_tracer.so -t 10 --ls_
but it says "_Missing application name_"
I don't know what is that. 
I also checked the sample code in the page (_pin -t obj/champsim_tracer.so -o traces/ls_trace.champsim -s 100000 -t 200000 -- ls_)
it calls for "_ls_trace.champsim_" which does not exist in my folder.
What's the deal here?

**Comment by ngober** [comment]
In the first issue, it appears you do not have a space between "--" and "ls", so the program cannot determine that it is "ls" you want to run.

In the second, PIN cannot create directories that don't exist, so you will need to run `mkdir traces` prior to running PIN.
