### ISSUE TITLE
There is a problem with new traces

### ISSUE THREAD

**Issue by OSangK** [ChampSim/ChampSim#174]
I made a new traces referring to ReadMe. Simulating the newly created trace on the master branch results without error.
However, when simulating in the develop branch, the following error occrus, but it is difficult to find the reason. That's why I write like this.

champsim: src/ooo_cpu.cc:956: void O3_CPU::execute_store(std::vector<LSQ_ENTRY>::iterator): Assertion `dependent->lq_index[j]->producer_id == sq_it->instr_id' failed.

![errormsg](https://user-images.githubusercontent.com/81791989/130561444-040384ef-ffbf-48fd-96fb-4519b4e7a95e.jpg)

**Comment by Yujie-Cui** [comment]
Hello, I would like to ask how to use Pin tool to generate my own trace. 

pin -t obj-intel64/champsim_tracer.so  -s 100000 -t 200000 -- execute_file
When generating the benchmark program for spec2006, do you choose the number of skip instructions based on SimPoint? How to generate SimPoint information? 

Thank you!
