### ISSUE TITLE
how to read CRC2 traces?

### ISSUE THREAD

**Issue by Shafayet-Anik** [ChampSim/ChampSim#179]
Hi,
Can you tell me how to read CRC2 traces?  
Suppose I want to read (bzip2_10M.trace). In the latest CRC, there is a header instruction.h, In that header there is a function print_instr(). How to run this function. Sorry for asking a simple question as I am not an expert.

**Comment by ngober** [comment]
The CRC traces cannot be read directly given the `instruction.h` header. ChampSim supplies the `tracereader` class in `tracereader.h`. Instances of this class can read the trace files and produce instances of `ooo_model_instr`, which can then be printed.
