### ISSUE TITLE
there are ambiguities when try to invalid tlb and cache

### ISSUE THREAD

**Issue by gxflying** [ChampSim/ChampSim#180]
https://github.com/ChampSim/ChampSim/blob/118459cfe900f39b05302c4ecda125d6d25ef88d/src/main.cc#L389

the virtual address is spilted as   
63---------------------------------------------------------------------11---------------0
| xxxx_xxxx_xxxx_xxxx_xxxx_xxxx_xxxx_xxxx_xxxx_xxxx_xxxx_xxxx_xxxx|xxxx_xxxx_xxxx|
------------------------------------------------------------------------  |xxxx_xx|xx_xxxx|
-------------------------------------------------------------------------**set idx**  | **block offset**
and the **mapped_ppage** here is the (virtual address >> LOG2_PAGE_SIZE ) 
so I think the **cl_addr** should be (mapped_ppage << (LOG2_PAGE_SIZE - LOG2_BLOCK_SIZE)), which is the virtual address without the block offset bits,  
the **BLOCK_SIZE** here is equal to (LOG2_PAGE_SIZE - LOG2_BLOCK_SIZE) but with wrong meanings
the magical value "**6**" here is equal to (LOG2_PAGE_SIZE - LOG2_BLOCK_SIZE) but with wrong meanings too !
if only we have a value of **BLOCK_SIZE** other then "**6**" the program will not work correctly !

            for (uint32_t i=0; i<**BLOCK_SIZE**; i++) {                   // should be changed to **(LOG2_PAGE_SIZE - LOG2_BLOCK_SIZE)**
                uint64_t cl_addr = (mapped_ppage << **6**) | i;      // should be  changed to **(LOG2_PAGE_SIZE - LOG2_BLOCK_SIZE)**
                ooo_cpu[cpu].L1I.invalidate_entry(cl_addr);
                ooo_cpu[cpu].L1D.invalidate_entry(cl_addr);
                ooo_cpu[cpu].L2C.invalidate_entry(cl_addr);
                uncore.LLC.invalidate_entry(cl_addr);
            }

**Comment by ngober** [comment]
This looks like it was resolved in the recent update. If it wasn't feel free to reopen this issue.
