### ISSUE TITLE
please help me, troubling with CACHE::handle_prefetch()  

### ISSUE THREAD

**Issue by w1nda** [ChampSim/ChampSim#188]
i think CACHE::handle_prefetch() should check whether PQ contains RQ's wanted data.
but in cache.cc  CACHE::handle_prefetch() [line 84 - line 902](https://github.com/ChampSim/ChampSim/blob/master/src/cache.cc#L841-L902), it checked whether Cache contains PQ's data at line 841-842, and if so, it will be treat as a cache hit at line 896-897, is this right?

**Comment by ngober** [comment]
A read miss can only be satisfied by a fill. The handle_prefetch() function only handles prefetch requests from either this level or upper levels.
