### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nikolaniko** [ChampSim/ChampSim#19]
Hello, 
I have been getting familiar with ChampSim and I have a few questions. 
Does prefetching happen on every instruction, or on demand access or demand miss? Is there a place to set my preference for when to prefetch? 
What is the line size implemented in the cache? 
Are all instructions simulated, or are only memory instructions simulated from the trace? 

Any answers are appreciated, any info on where I could find the answers to these questions in the code would also be appreciated!
Thanks, 
Nick

**Comment by GinoAC** [comment]
Currently, prefetching occurs on an access to the cache, regardless of whether its a hit or a miss. When implementing your prefetcher in l2c_prefetcher_operate, you can use the information about the type of request and whether the access is a hit or a miss to prefetch at your preference. 
The cache line size of ChampSim after downloading is 64B, but is reconfigurable.
Only memory instructions are fully simulated.
