### ISSUE TITLE
Deadlock on STLB Merge

### ISSUE THREAD

**Issue by ST-mrl** [ChampSim/ChampSim#2]
Suggest inserting additional check into PACKET_QUEUE::check_queue lines 20, 42, 62 to verify that entry[i].instruction == packet->instruction. 

This is a workaround for an issue where requests simultaneously reach STLB from the ITLB and DTLB for the same address. They get merged, and then when the request is filled, only the first parent is notified, starving the other and causing deadlock.

**Comment by ChampSim** [comment]
This one is a good catch. We'll investigate this issue further. If you have an example trace that shows this deadlock issue, please share it with us so that we can resolve this issue more quickly.

**Comment by ngober** [comment]
I'm closing this because it was probably fixed in #87. If it was not, let me know and we can look into it again.
