### ISSUE TITLE
ITLB and L1I access

### ISSUE THREAD

**Issue by alberto-ros** [ChampSim/ChampSim#213]
¡Hi everyone! 

I noticed two features in the implementation of the fetch stage which raised some questions to me.

The first one is that the L1I is accessed after the ITLB offers the translation. This way the L1I is modelled as a physically indexed, physically tagged (PIPT) cache. Would not be more realistic to model a virtually indexed, physically tagged (VIPT) cache? That is, to overlap the ITLB access with the L1I access.

The second one is that the implementation assumes that the ITLB and the L1I have only one read port. My question here is if this is the standard in current processor, e.g., Sunny Cove (as the default parameters try to mimic that processor).

Thanks always for your time!
Alberto

**Comment by ngober** [comment]
This is something that I'm working on right now. It has been a problem for some time that the TLBs and the caches operate in series. It's taking a bit of work to separate the two. Hopefully I will have something to PR in the next couple weeks.

Your second point about there only being one read port is a good point, and I hadn't considered it. I'll make that a next step after the parallel TLB access.

**Comment by ngober** [comment]
The parallel TLB access is enabled with #227.

**Comment by GinoAC** [comment]
I'm going to go ahead and close this since it looks like the issues are resolved in #227 and #217.
