### ISSUE TITLE
Current champsim inclusive or not?

### ISSUE THREAD

**Issue by pranjaljain9** [ChampSim/ChampSim#267]
Can someone confirm if this champsim is inclusive or not? If not then how do we make it inclusive. Kindly help.

**Comment by dingqy** [comment]
Same question.

I heard that it's non-inclusive non-exclusive cache and I plan to make it inclusive / exclusive.

**Comment by ngober** [comment]
ChampSim is non-inclusive. The simulator currently makes no guarantees about clusivity in either direction. I've heard requests for strict inclusivity or exclusivity, and I always welcome pull requests to implement these.
