### ISSUE TITLE
Anyway to open/modify champsim trace file?

### ISSUE THREAD

**Issue by pranjaljain9** [ChampSim/ChampSim#272]
I have created my own trace file using pintool, but I want to open the trace file and modify it. But the problem is that the trace file is in encoded format. Is there some way through which I can modify the trace file?

**Comment by ngober** [comment]
There is no tool I am aware of that will directly edit the trace files. They are a binary encoding and not designed to be hand-edited. If you want to edit the trace files, you will need to write a program to do it.
