### ISSUE TITLE
How to insert dummy instructions in read queue?

### ISSUE THREAD

**Issue by gangwarady** [ChampSim/ChampSim#273]
I want to add some dummy instructions between 2 trace instructions. I don't want to do it through the trace, instead I directly want to add these dummy instructions from champsim. On pushing a dummy packet on RQ, I'm getting segmentation fault error. No idea why this error happens. Can anybody help?

**Comment by GinoAC** [comment]
By read queue are you referring to the cache model or are you adding the instructions directly into the front-end model?

**Comment by gangwarady** [comment]
In cache.cc file and in add_rq(PACKET*) function, while pushing the packet in RQ, I simply change the physical address of the packet or give a dummy physical address and then push_back it in the RQ. This is resulting in segmentation fault error.

**Comment by GinoAC** [comment]
I'm not sure if this is your goal, but just to warn you, this will only simulate dummy cache requests not dummy instructions which would interact with the frontend.

I recommend using gdb to narrow down where the segmentation fault is originating. Make sure none of your requests have an address of `0` as this is not handled in the cache model.

**Comment by ngober** [comment]
I'll second what Gino said. I wouldn't be surprised if this is a hard problem to solve. The system is currently set up with the assumption that every request is meaningful. There's probably countless places where this is implicit, and tracking them down will be tricky. I would add a ton of assertions to make sure that the dummy instructions do what you want.
