### ISSUE TITLE
Data overwrite in handle_writeback()

### ISSUE THREAD

**Issue by dingqy** [ChampSim/ChampSim#276]
Hi,

Sorry for asking this question. I am reading Cache codes and have a question for handle_writeback(). When write request hit the cache block, why doesn't it update the data in the block? Is there anything I miss? Thank you!

if (way < NUM_WAY) // HIT
{
  impl_replacement_update_state(handle_pkt.cpu, set, way, fill_block.address, handle_pkt.ip, 0, handle_pkt.type, 1);

  // COLLECT STATS
  sim_hit[handle_pkt.cpu][handle_pkt.type]++;
  sim_access[handle_pkt.cpu][handle_pkt.type]++;

  // mark dirty
  fill_block.dirty = 1;
}

**Comment by ngober** [comment]
What action would you expect that the model would take on a write hit? As it stands, the block is marked as dirty (that is, having been written to), and no further action is taken.

**Comment by dingqy** [comment]
Sorry for such stupid question. I am new to simulator.

I also check the retire_rob(). It seems that store data is not considered in this simulation. So it only simulate the write request without any actual data update, right?

I mean whether there are such codes to update the cache block.
fill_block.data = handle_pkt.data;

**Comment by ngober** [comment]
You're correct. No actual data is contained in the traces. The simulator only tracks the presence of the blocks. The `PACKET::data` field is used in the translation path to provide the VA/PA mapping.

**Comment by dingqy** [comment]
Got it. Thank you!
