### ISSUE TITLE
Register Renaming 

### ISSUE THREAD

**Issue by Jazeeeb** [ChampSim/ChampSim#28]
Hello 
I'm pretty known to Champsim and just started going through the source code but I was wondering if anyone knows about if Champsim has any register renaming to eliminate false dependencies? and what is the range of numbers assigned to logical registers to do the register renaming?

Thanks

**Comment by sethpugsley** [comment]
There is no register renaming scheme, but ChampSim doesn't even attempt to detect WAR or WAW conflicts.  Instructions are only marked as dependent on one another if there's a RAW conflict.  This is similar to a register renaming scheme with an infinite number of physical registers.  If you're interested in studying register renaming, you'll have to add that system in yourself.
