### ISSUE TITLE
Small typo leading to incorrect ICache stats

### ISSUE THREAD

**Issue by sawansib** [ChampSim/ChampSim#283]
I found a small typo at [cache.cc](https://github.com/ChampSim/ChampSim/blob/37a418491c776bfceb3b91995b17d56cdec14c6d/src/cache.cc#L491) where the stats of ICache are wrongly calculated. It can be simply solved by replacing "hits" by "misses".

Sawan

**Comment by ngober** [comment]
Hmm, that's a good catch. Would you please submit a pull request and we'll patch that up.

**Comment by sawansib** [comment]
[https://github.com/ChampSim/ChampSim/pull/284](Here) is the pull request. 

Sawan
