### ISSUE TITLE
MacroOp or MicroOp

### ISSUE THREAD

**Issue by Jazeeeb** [ChampSim/ChampSim#29]
Hello
does the Champsim read macroops from the trace  (CRC-2 traces) and then converts them into microops? if so, at which stage that happens?

**Comment by ngober** [comment]
ChampSim reads macro-ops from the traces, but does not attempt to decode them into micro-ops. It assumes that the process of decoding and fusing micro-ops results in an average of 1 micro-op per macro-op. This may not be a valid assumption. A way to mitigate this might be to implement a function in `src/ooo_cpu.cc` that reads from the decode buffer, then issues one or more `ooo_model_instr`s to the ROB with particular latencies according to a table like [this one](https://www.uops.info/table.html). That might be a worthy project to try.
