### ISSUE TITLE
Possible mistake in filllike_miss()

### ISSUE THREAD

**Issue by dchasap** [ChampSim/ChampSim#310]
Hi,
I am not sure but I think there is a small mistake in the filllike_miss funtion in cache.c
On line 325, there is the line   writeback_packet.instr_id = handle_pkt.instr_id;  I think it should be   writeback_packet.instr_id = fill_block.instr_id;
If I understand correctly, the writeback_packet should contain the info from the block to be evicted, which is fill_block.

**Comment by ngober** [comment]
It depends on how you're viewing the nature of the writeback packet. The instruction ID is only used in replacement policies, and there it is viewed mostly as a sequence number. If we view it as a sequence number, it probably makes more sense to use the ID which caused the eviction, or else the numbers could be very discontinuous. I can see arguments from both sides on this, and so my inclination is to leave it as-is.
