### ISSUE TITLE
Possible mistake in readlike_miss().

### ISSUE THREAD

**Issue by Chen-zixiao** [ChampSim/ChampSim#317]
File cache.cc line 265 checks the occupancy without increasing RQ_FULL and PQ_FULL.
After that on line 280, the function add_rq and add_rq are called, which also checks the occupancy but tries to set *_FULL.

**Comment by ngober** [comment]
It looks like commit 744f79bb4c401e504b041e553c1c09dcba4911ff fixed this on the develop branch. It will be fixed in the next merge.
