### ISSUE TITLE
question about PageTableWalker class

### ISSUE THREAD

**Issue by arcturus812** [ChampSim/ChampSim#336]
Hello ChampSim Developers

I am relatively new to using ChampSim and have been analyzing my code to identify any potential issues. In the process, I would like to seek your expertise and input.

Upon examining line 134 of ptw.cc, I noticed that there might be an inconsistency with the page table walking mechanism. It appears that the comparison statement's PagingStructureCache should be marked as PSCL3 instead.

I would appreciate any insights or opinions from the development team on this matter. Please let me know if I am on the right track or if there are any additional considerations I should be aware of.

Thank you for your assistance and I look forward to your response.

```
  if (fill_mshr->translation_level == PSCL5.level)
          PSCL5.fill_cache(addr, fill_mshr->v_address);
        if (fill_mshr->translation_level == PSCL4.level)
          PSCL4.fill_cache(addr, fill_mshr->v_address);
        if (fill_mshr->translation_level == PSCL2.level) // should be PSCL3 ?
          PSCL3.fill_cache(addr, fill_mshr->v_address);
        if (fill_mshr->translation_level == PSCL2.level)
          PSCL2.fill_cache(addr, fill_mshr->v_address);
```

**Comment by ngober** [comment]
You're correct. This was resolved in #206 and will be merged in the next release, which should be in a month or so.
