### ISSUE TITLE
Processor writes do not call L1D prefetcher_cache_operate in develop branch

### ISSUE THREAD

**Issue by alberto-ros** [ChampSim/ChampSim#338]
Hello,

While doing some tests in the current develop branch I noticed that processor writes  (WRITE to L1D) never call the prefetcher_cache_operate function of the L1D prefetcher, even though the configuration file specifies: 

   "L1D": {
        ...
        "prefetch_activate": "LOAD,WRITE",
        ....
    },

Is this an intended behavior or a bug?

**Comment by ngober** [comment]
That's definitely a bug. I was confused for a moment because the call to `prefetcher_cache_operate` happens in the tag check, which writes definitely undergo. The bug is a configuration bug where the script expected "WRITEBACK", not "WRITE". I've submitted a pull request that fixes this.
