### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by MathanMK** [ChampSim/ChampSim#358]
**Describe the bug**
I have tried to run a basic trace file which adds two arrays. I have encountered an assertion bug which states the packet address is 0.

**To Reproduce**
1. Go to  [array.zip](https://github.com/ChampSim/ChampSim/files/11709869/array.zip)
2. Run the champsim trace file -  bin/champsim --warmup_instructions 0 --simulation_instructions 2878700 array.champsimtrace.xz > array.out 

**Output**
The assertion error I have encountered:
![image](https://github.com/ChampSim/ChampSim/assets/74282406/2c6fe00a-c7c4-45ae-aede-b2378322d73a)

**Desktop (please complete the following information):**
 - OS: RedHat Enterprise Linux
 - Compiler GCC 7.3.0
 - Version 7.9

**Comment by ngober** [comment]
I may have found the bug that caused this. Would you please checkout `358-assertion-error` and see if it resolves your issue?
