### ISSUE TITLE
*** Reached end of trace: ./tracer/pin/champsim.trace.gz

### ISSUE THREAD

**Issue by JimmyWong1998** [ChampSim/ChampSim#376]
Hi ChampSim expert,

I created my own trace file following your instruction but when I ran this trace file in ChampSim, I got the following:

*** Reached end of trace: ./tracer/pin/champsim.trace.gz
*** Reached end of trace: ./tracer/pin/champsim.trace.gz
*** Reached end of trace: ./tracer/pin/champsim.trace.gz
*** Reached end of trace: ./tracer/pin/champsim.trace.gz
*** Reached end of trace: ./tracer/pin/champsim.trace.gz
*** Reached end of trace: ./tracer/pin/champsim.trace.gz
*** Reached end of trace: ./tracer/pin/champsim.trace.gz

Is that a correct output? How do I fix it?

Thank you,
Jimmy

**Comment by ngober** [comment]
Your trace file is probably very small. If you specify `-i` when running ChampSim, it will repeat the trace as many times as necessary to reach the number of specified instructions (see #342).

**Comment by JimmyWong1998** [comment]
Many thanks! I got it.

Jimmy

**Comment by JimmyWong1998** [comment]
Many thanks! I got it.

Jimmy
