### ISSUE TITLE
where is folder fmt ?

### ISSUE THREAD

**Issue by Xiaofeng-Hill** [ChampSim/ChampSim#407]
Hello ,

I am quite new to programing and try to compile the ChampSim.
But it said below. I understand this project is very popular and should not have such issue. But what is the reason behind ?

.../ChampSim-master/src/cache.cc:24:10: fatal error: fmt/core.h: No such file or directory
   24 | #include <fmt/core.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:49: /home/lixiaof/CacheTest/ChampSim-master/.csconfig/2fca8aec/obj/cache.o] Error 1

Thanks a lot,
Xiaofeng

**Comment by wilsonwang881** [comment]
Have you run the following lines to install dependencies via vcpkg?

```
git submodule update --init
vcpkg/bootstrap-vcpkg.sh
vcpkg/vcpkg install
```

You should see a folder `./vcpkg_installed/x64-linux/share/fmt/`.
