### ISSUE TITLE
use doubt:  IPC before and after warm up 

### ISSUE THREAD

**Issue by Maxpicca-Li** [ChampSim/ChampSim#461]
run env:
* env: MacOs Ventura 13.3
* test: DPC-3/400.perlbench-41B.champsimtrace.xz
* config: default config of master
* commend:
```shell
bin/champsim --warmup_instructions 200000000 --simulation_instructions 500000000 ./DPC-3/400.perlbench-41B.champsimtrace.xz
```

doubt:

* Why is there such a big gap between IPC before and after warming up?
* Logically, the IPC should be lower before the warm-up.
<img width="952" alt="image" src="https://github.com/ChampSim/ChampSim/assets/60693260/8860d7fa-5f9f-4b49-8b4c-be04c14d69ec">

**Comment by ngober** [comment]
You say that logic demands the IPC should be lower in the warmup, but it is not clear why that should be the case. In the warmup phase, most latencies are skipped, then the statistics are discarded. The final statistics reported consist only of non-warmup phases.

**Comment by Maxpicca-Li** [comment]
I got that, thank you very much.

As for the lower IPC in warm-up, both the cache and the prefetcher will be cold-started during the warm-up phase, so the normal IPC will be lower. It turns out that the IPC calculation in warmup phase is not the same as the normal calculation, thank you for the answer.
