### ISSUE TITLE
High DRAM latencies - Potential bug in DRAM scheduling logic

### ISSUE THREAD

**Issue by ShreyanJabade** [ChampSim/ChampSim#465]
**Describe the bug**
Very high DRAM latencies showing up in spite of few memory requests. 

**To Reproduce**
1. Run any benchmark
2. Monitor LLC miss latencies

**Location in code**
dram_controller.cc:

```
auto next_schedule = [](const auto& lhs, const auto& rhs) {
      return !(rhs.has_value() && !rhs.value().scheduled) || ((lhs.has_value() && !lhs.value().scheduled) && lhs.value().event_cycle < rhs.value().event_cycle);
    };
```

    DRAM_CHANNEL::queue_type::iterator iter_next_schedule;
    if (channel.write_mode)
      iter_next_schedule = std::min_element(std::begin(channel.WQ), std::end(channel.WQ), next_schedule);
    else
      iter_next_schedule = std::min_element(std::begin(channel.RQ), std::end(channel.RQ), next_schedule);

**Issue**
While finding the next candidate to be scheduled, the above piece of code will set the next candidate (iter_next_schedule) as the oldest packet (based on event cycle) in the RQ. The issue arises when the bank for that particular packet is busy. It will stall the entire RQ even though the subsequent packets' banks are idle. This is demonstrated in the following log which prints state of the channel.RQ and iter_next_schedule at each cycle.

![image](https://github.com/ChampSim/ChampSim/assets/58798198/de2c4010-b6ba-4223-8901-15dea2eb9090)

**Expected behavior**
This in-order head of queue blocking while scheduling seems to be unintentional, since older versions of Champsim (pre-2021) do not face this issue.  

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Compiler: gcc

**Comment by maccoymerrell** [comment]
I believe this was resolved with this pull into develop. Can you confirm?
https://github.com/ChampSim/ChampSim/pull/383

**Comment by maccoymerrell** [comment]
Yes, that test was added to verify the scheduler was behaving properly.

**Comment by ShreyanJabade** [comment]
Yes, this does fix the issue. Thank you. Will this be merged with the master branch later? Or is the scheduling logic in master branch intentional?

**Comment by ngober** [comment]
Yes, the development work will eventually make its way into master, but slowly and steadily. If the current pace continues, it will probably be a month or so until the next release candidate.

**Comment by ShreyanJabade** [comment]
Right. Thank you
