### ISSUE TITLE
Creating own traces

### ISSUE THREAD

**Issue by raffael-daltoe** [ChampSim/ChampSim#508]
Issue Description
I am attempting to create my own trace using a simple C code. Below is the code I'm using:

```
int main() {
    int a = 0, b = 0, c = 0;
    int i = 0;
    while (i < 1000) {
        a = a + b + c;
        b += 5;
        c += b + c;
        i++;
    }
}
```

then i compile and generate the executable "test".

I use the following command to generate a trace using Intel Pin:

pin -t obj-intel64/champsim_tracer.so -o traces/test.champsim -s 100000 -t 100000000 -- codes/test

The generated .champsim file is compressed to .xz format with:

xz -z test.champsim

I run the ChampSim simulator with the following command:

/PFE/tools/ChampSim$ bin/champsim --warmup_instructions 200000000 --simulation_instructions 500000000 tracer/pin/traces/test.champsim.xz 

When running the simulation, I receive these warnings:

WARNING: physical memory size is smaller than virtual memory size.
WARNING: option --warmup_instructions is deprecated. Use --warmup-instructions instead.
WARNING: option --simulation_instructions is deprecated. Use --simulation-instructions instead.

*** ChampSim Multicore Out-of-Order Simulator ***
Warmup Instructions: 200000000
Simulation Instructions: 500000000
Number of CPUs: 1
Page size: 4096

Off-chip DRAM Size: 4 GiB Channels: 1 Width: 64-bit Data Race: 3200 MT/s

However, the simulation doesn't proceed as expected and only displays the following message:

*** Reached end of trace: (0, "tracer/pin/traces/test.champsim.xz")
*** Reached end of trace: (0, "tracer/pin/traces/test.champsim.xz")
*** Reached end of trace: (0, "tracer/pin/traces/test.champsim.xz")
*** Reached end of trace: (0, "tracer/pin/traces/test.champsim.xz")
*** Reached end of trace: (0, "tracer/pin/traces/test.champsim.xz")

I'm using:
gcc (Ubuntu 11.4.0-2ubuntu1~20.04) 11.4.0
clang version 10.0.0-4ubuntu1
cmake version 3.30.2
Pin: pin-3.15-98253-b56e429b1

The simulation does not run beyond recognizing the end of the trace, and I am unsure how to proceed. I have also attempted to use a trace converter, but it did not resolve the issue.

Does anyone have suggestions on how to fix this or troubleshoot further?

**Comment by maccoymerrell** [comment]
That message means ChampSim has reached the end of the trace file.

A couple questions:

1. What size is the output file from the tracer? Uncompressed, it should be around 64 * number of instructions you traced.
2. How long did you let the tracer run for? It can take a while to run depending on your machine, so if it stopped before you got to the part of the program you want to trace the file will be very small or even empty.

**Comment by raffael-daltoe** [comment]
1. PFE@raffael:/PFE/tools/ChampSim/tracer/pin/traces$ ll
total 772
drwxr-xr-x 2 PFE PFE   4096 Sep 30 15:34 ./
drwxr-xr-x 5 PFE PFE   4096 Sep 30 15:31 ../
-rw-r--r-- 1 PFE PFE 779840 Sep 30 15:34 test.champsim


When I ran the executable, it doesn't behave as expected, above is the output i receive. Despite the issues, I am confident that the problem is not with the hardware since the machine is an i9-14900HX

**Comment by maccoymerrell** [comment]
Try making your for-loop longer (more iterations). Based on the length of your program, its possible that you are skipping over the entire program by specifying -s 100000 in pin.

**Comment by ngober** [comment]
Note that `*** Reached end of trace: (0, "tracer/pin/traces/test.champsim.xz")` is not an error message. Your trace is much smaller than the 500M instructions you have specified, so ChampSim is repeating the workload. You can run a single instance of the trace by omitting `--warmup_instructions 200000000 --simulation_instructions 500000000` from your invocation.

**Comment by raffael-daltoe** [comment]
Oh, seriously, the problem was the skipped instructions, now everything is working.
Thank you so much !
