### ISSUE TITLE
CACHE latency key does not modify latency

### ISSUE THREAD

**Issue by maccoymerrell** [ChampSim/ChampSim#524]
**Describe the bug**
The "latency" field in caches within ChampSim's config file and cache builder does not get used when using a cache default build.
As a result, changing the latency field in the config for any cache has no effect.

**To Reproduce**
1. Pull develop
2. Create a champsim config with non-default cache latencies
3. Config, build, and run

**Expected behavior**
The cache latency is altered by the configuration.

**Output**
Latency remains unchanged, regardless of what value is chosen.

**Comment by ngober** [comment]
The root cause of this is [here](https://github.com/ChampSim/ChampSim/blob/aa336e838027563196eeb721be027f48d63a1b39/inc/defaults.hpp#L63). All of the default cache configurations use `hit_latency` and `fill_latency`, which means they ignore any specified `latency`.
