### ISSUE TITLE
 how to download spec？

### ISSUE THREAD

**Issue by mao-l** [ChampSim/ChampSim#66]
I can't download spec，
Whenever I enter the http://hpca23.cse.tamu.edu/champsim-traces/speccpu/ ，prompt me “You don't have permission to access this resource”.
How do I download it?

**Comment by GinoAC** [comment]
Hi @mao-l, the traces should now be accessible at the same URL.

**Comment by mao-l** [comment]
> Hi @mao-l, the traces should now be accessible at the same URL.

yes, Thank you for your help.
