### ISSUE TITLE
How to make champsim inclusive ? Its very important for me . If anyone knows please tell me ASAP

### ISSUE THREAD

**Issue by sujeetc** [ChampSim/ChampSim#7]

**Comment by itisntalex** [comment]
Hey @sujeetc First of all, what do you mean by "inclusive"?

**Comment by sujeetc** [comment]
I mean cache hierarchy L1 , l2 and LLC should be inclusive.

**Comment by itisntalex** [comment]
Hey @sujeetc. Sorry for the late late answer, but in fact I don't really know... I just had my hands on it since a few months and I'm still discovering new things everyday. Hope you found a solution to your issue and if not, that you will. :+1:

**Comment by ChampSim** [comment]
Inclusiveness needs to be guaranteed by sending an eviction signal from upper-level cache to the lower level caches. You can start by adding extra function something like send_evict_signal().
