### ISSUE TITLE
ChampSim build Failed : Line 100 and 101 Command Not found while executing build_ChampSim.sh

### ISSUE THREAD

**Issue by dwarakanadhas** [ChampSim/ChampSim#77]

**Comment by GinoAC** [comment]
This appears to mean that you do not have **make** installed on your machine. Try installing it and see if that resolves the issue.

**Comment by dwarakanadhas** [comment]
Thanks for your reply. Can you please elaborate?

**Comment by GinoAC** [comment]
Line 100/101 includes the make command, which runs the Makefile included with ChampSim. Since the make command is not found, it may mean you do not have make installed on the computer you're building ChampSim on and you will need to install it to successfully complete the build script.

**Comment by dwarakanadhas** [comment]
Got it... Thank u so much for ur reply. I will install make and try to execute.

**Comment by dwarakanadhas** [comment]
i have installed make file and tried to execute. it is giving the same error.

**Comment by GinoAC** [comment]
Are you still having this issue? If so, what OS are you trying to compile on?
