### ISSUE TITLE
Results question

### ISSUE THREAD

**Issue by nikolaniko** [ChampSim/ChampSim#81]
![image](https://user-images.githubusercontent.com/56739537/98599623-49a0ed00-22aa-11eb-85c7-5636e9acd45c.png)

Hi all,

I have some questions regarding the results, specifically for the prefetch data of L2:
1)	What is the difference between L2C prefetch hit, and L2C prefetch useful? Are they different values because a prefetched block can be hit more than once, but only counted as a useful prefetch once? 
2)	Since the L2C prefetcher is prefetch on demand, why aren’t L2C load access and L2C prefetch requested the same value? 
3)	Is coverage of L2C prefetch calculated by L2C prefetch Hit / L2C Load access? Or L2C prefetch useful / L2C load access? 
4)	Is accuracy of L2C prefetch calculated by L2C Prefetch Hit / L2C prefetch access? 
Also, is there a document that explains the results metrics? 

Thank you, 
Nick

**Comment by ngober** [comment]
A prefetch hit and a useful prefetch are different things. A prefetch hit is a hit by a prefetch in the cache, that is, a prefetch was issued for a block that is present in the cache. A useful prefetch is a prefetch, previously filled, that is hit by a (non-prefetch) demand. A block can only be marked as being useful once.

I presume for your second question that you are using a next-line prefetcher. This prefetcher is a prefetch-on-demand prefetcher, however, there may be prefetches that are not issued if the prefetch queue is full (note that L1 prefetch misses are issued to the L2 PQ, so they may contend for resources if you are aggressively prefetching in the L1), or if the prefetch crosses a page boundary.

As to your final questions, coverage is conventionally viewed as the fraction of misses prevented, or the ratio of useful prefetches to misses in the absence of prefetching, and accuracy is the fraction of prefetches that are useful, or the ratio of useful prefetches to issued prefetches. There is some degree of variation and disagreement over the precise definition of these metrics, though, so it is worth being clear in your presentation of the results.
